# Generated by Django 5.0.7 on 2024-08-25 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0004_alter_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
    ]
