# Generated by Django 5.0.7 on 2024-08-25 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0007_payroll_allowances_payroll_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payroll',
            name='pay_period_end',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='pay_period_start',
        ),
    ]
