# Generated by Django 5.0.7 on 2024-09-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0010_alter_department_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date', 'is_present')},
        ),
    ]
