# Generated by Django 5.0.7 on 2024-09-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emsapp', '0011_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together={('employee', 'month', 'status')},
        ),
    ]
